# Generated by Django 6.1.1 on 2026-09-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Taom', 'verbose_name_plural': 'Taomlar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Buyurtma elementi', 'verbose_name_plural': 'Buyurtma elementlari'},
        ),
        migrations.AddField(
            model_name='order',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='turi',
            field=models.CharField(choices=[('lavash', 'Lavash'), ('ichimlik', 'Ichimlik'), ('shirinlik', 'Shirinlik'), ('disser', 'Disser'), ('ovqat', 'Ovqat'), ('snak', 'Snak')], max_length=50),
        ),
    ]
