"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loyihaning maxfiy kaliti
SECRET_KEY = "django-insecure-key-for-project"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1t0cd6bd@ivcfubb@=55njss(2spsz@uo)5ih(lt!lqf5g^*oe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# Loyihaga ulangan barcha ilovalar va kutubxonalar ro'yxati
INSTALLED_APPS = [
    "django.contrib.admin",  # Django admin paneli
    "django.contrib.auth",  # Autentifikatsiya tizimi
    "django.contrib.contenttypes",  # Kontent turlari tizimi
    "django.contrib.sessions",  # Sessiyalarni boshqarish
    "django.contrib.messages",  # Xabarlarni ko'rsatish
    "django.contrib.staticfiles",  # Statik fayllar (CSS, JS) bilan ishlash
    # Tashqi kutubxonalar (Third-party)
    "rest_framework",  # Django REST Framework
    "rest_framework_simplejwt",  # JWT kutubxonasi
    "django_filters",  # Filterlash vositasi
    "drf_spectacular",  # Swagger vositasi
    "corsheaders",  # CORS header larni boshqarish
    # Mahalliy ilova
    "core",  # Asosiy biznes mantiq ilovasi
]

# So'rov va javoblar orasida ishlaydigan vositachi dasturlar
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # CORS ni eng birinchi tekshirish
    "django.middleware.security.SecurityMiddleware",  # Xavfsizlik sozlamalari
    "django.contrib.sessions.middleware.SessionMiddleware",  # Sessiyalar xizmati
    "django.middleware.common.CommonMiddleware",  # Umumiy middleware
    "django.middleware.csrf.CsrfViewMiddleware",  # CSRF hujumlaridan hidoyat
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # Foydalanuvchini aniqlash
    "django.contrib.messages.middleware.MessageMiddleware",  # Xabarlarni yetkazish
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # Clickjacking dan himoya
]
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Ma'lumotlar bazasi sozlamasi (SQLite3)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",  # Baza drayveri
        "NAME": BASE_DIR / "db.sqlite3",  # Baza fayli joylashuvi
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}



import logging
from datetime import timedelta



# Standart User o'rniga maxsus core.User modelini belgilash[cite: 1]
AUTH_USER_MODEL = "core.User"

# REST Framework ning global sozlamalari
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # Odatiy auth JWT bo'ladi
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",  # Swagger sxemasi generatori
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",  # Sahifalash turi
    "PAGE_SIZE": 10,  # Har bir sahifada 10 tadan ma'lumot qaytariladi
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",  # Odatiy filter backend
    ),
}

# Swagger UI sozlamalari
SPECTACULAR_SETTINGS = {
    "TITLE": "Ovqat Buyurtma API",  # Dokumentatsiya sarlavhasi
    "DESCRIPTION": "Ovqat buyurtma qilish backend REST API hujjatlari",  # Tavsifi
    "VERSION": "1.0.0",  # Versiyasi
}

# Barcha manbalardan kelgan so'rovlarga ruxsat berish (CORS)
CORS_ALLOW_ALL_ORIGINS = True

# Tizim hodisalarini logga yozish (Logging) sozlamasi
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",  # Log formati
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",  # Konsolga chiqarish darajasi
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "INFO",  # Faylga yozish darajasi
            "class": "logging.FileHandler",
            "filename": "app.log",  # Log saqlanadigan fayl
            "formatter": "verbose",
        },
    },
    "loggers": {
        "core": {
            "handlers": ["console", "file"],  # Ikkala handlerga yuboriladi
            "level": "INFO",
            "propagate": True,
        },
    },
}

LANGUAGE_CODE = "en-us"  # Tizim tili
TIME_ZONE = "UTC"  # Vaqt zonasi
USE_I18N = True  # Internatsionalizatsiya
USE_TZ = True  # Vaqt zonalaridan foydalanish
STATIC_URL = "static/"  # Statik fayllar URL manzili
DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"  # Avto-ID lar uchun standart maydon
)